### ISSUE TITLE
Insert INTO hat keine Bedeutung? 

### ISSUE THREAD

**Issue by derech1e** [derech1e/LernsituationSQL#11]
Bitte bei T-SQL prüfen

**Comment by Nichtmetall** [comment]
Ja, insert INTO hat keine Bedeutung. Ist nur ein Syntax Ding. 
https://stackoverflow.com/questions/233919/insert-vs-insert-into

**Comment by derech1e** [comment]
> Ja, insert INTO hat keine Bedeutung. Ist nur ein Syntax Ding. 
> 
> https://stackoverflow.com/questions/233919/insert-vs-insert-into

Ok, Top👍🏻
